name: ProtectionBlocks
version: '${version}'
main: t.me.p1azmer.plugin.protectionblocks.ProtectionPlugin
api-version: '1.20'
author: "plazmer"
description: "Custom private region via blocks"
depend: [PLAZMER-ENGINE]
folia-supported: true