name: ProtectionBlocks
version: '${version}'
main: t.me.p1azmer.plugin.protectionblocks.ProtectionPlugin
api-version: '1.17'
author: "plazmer"
description: "Custom private region via blocks"
folia-supported: true
load: POSTWORLD
depend: [ PLAZMER-ENGINE ]
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - FancyHolograms
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8